version: '3.8'

services:
  my-s3-clone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-s3-clone
    ports:
      - "9090:9090"
    volumes:
      - ./buckets:/mydata/data 
    networks:
      - mynetwork

      
networks:
  mynetwork:
    driver: bridge
