version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - mynetwork

  my-s3-clone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-s3-clone
    ports:
      - "9090:9090"
    volumes:
      - ./buckets:/mydata/data 
    depends_on:
      - minio
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - mynetwork

  artillery:
    image: node:18-alpine  # Utiliser une image Node.js pour installer Artillery
    container_name: artillery
    working_dir: /usr/src/app
    volumes:
      - ./tests:/usr/src/app  # Dossier contenant les fichiers de test Artillery
      - ./reports:/usr/src/app/reports  # Dossier pour les rapports
    networks:
      - mynetwork
    depends_on:
      - my-s3-clone
    command: >
      sh -c "npm install -g artillery && artillery run test.yaml --output reports/report.json && artillery report --output reports/report.html reports/report.json"
      
networks:
  mynetwork:
    driver: bridge
