apiVersion: v1  # Version de l'API utilisée pour les objets de type Service
kind: Service  # Déclare que cet objet est un Service
metadata:
  name: my-s3-clone-service  # Nom du Service, utilisé pour référencer ce service dans d'autres objets (par exemple dans un Ingress)

spec:
  selector:  # Le Service sélectionne les pods qui ont les labels spécifiés ci-dessous
    app: my-s3-clone  # Label correspondant aux pods gérés par le Service
    owner: alizea  # Label supplémentaire pour filtrer les pods appartenant à l'utilisateur spécifié

  ports:
    - protocol: TCP  # Protocole utilisé par le Service (ici TCP)
      port: 9090  # Port que le Service expose à l'intérieur du cluster
      targetPort: 9090  # Port sur lequel les pods écoutent (doit correspondre au `containerPort` du Deployment)

  type: ClusterIP  # Le type "ClusterIP" signifie que le Service est accessible uniquement à l'intérieur du cluster
